export interface Upazila {
  id: string
  name: string
}

export interface District {
  id: string
  name: string
  division: string
  upazilas: Upazila[]
}

export const BD_DISTRICTS: District[] = [
  {
    id: 'dhaka',
    name: 'ঢাকা',
    division: 'ঢাকা',
    upazilas: [
      { id: 'dhaka-sadar', name: 'ঢাকা সদর' },
      { id: 'dhamrai', name: 'ধামরাই' },
      { id: 'dohar', name: 'দোহার' },
      { id: 'keraniganj', name: 'কেরানীগঞ্জ' },
      { id: 'nawabganj', name: 'নবাবগঞ্জ' },
      { id: 'savar', name: 'সাভার' },
    ],
  },
  {
    id: 'gazipur',
    name: 'গাজীপুর',
    division: 'ঢাকা',
    upazilas: [
      { id: 'gazipur-sadar', name: 'গাজীপুর সদর' },
      { id: 'kaliakair', name: 'কালিয়াকৈর' },
      { id: 'kaliganj-gz', name: 'কালীগঞ্জ' },
      { id: 'kapasia', name: 'কাপাসিয়া' },
      { id: 'sreepur', name: 'শ্রীপুর' },
    ],
  },
  {
    id: 'narayanganj',
    name: 'নারায়ণগঞ্জ',
    division: 'ঢাকা',
    upazilas: [
      { id: 'narayanganj-sadar', name: 'নারায়ণগঞ্জ সদর' },
      { id: 'araihazar', name: 'আড়াইহাজার' },
      { id: 'bandhu', name: 'বন্দর' },
      { id: 'rupganj', name: 'রূপগঞ্জ' },
      { id: 'sonargaon', name: 'সোনারগাঁ' },
    ],
  },
  {
    id: 'manikganj',
    name: 'মানিকগঞ্জ',
    division: 'ঢাকা',
    upazilas: [
      { id: 'manikganj-sadar', name: 'মানিকগঞ্জ সদর' },
      { id: 'daulatpur', name: 'দৌলতপুর' },
      { id: 'ghior', name: 'ঘিওর' },
      { id: 'harirampur', name: 'হরিরামপুর' },
      { id: 'saturia', name: 'সাটুরিয়া' },
      { id: 'shivalaya', name: 'শিবালয়' },
      { id: 'singair', name: 'সিঙ্গাইর' },
    ],
  },
  {
    id: 'munshiganj',
    name: 'মুন্সীগঞ্জ',
    division: 'ঢাকা',
    upazilas: [
      { id: 'munshiganj-sadar', name: 'মুন্সীগঞ্জ সদর' },
      { id: 'gazaria', name: 'গজারিয়া' },
      { id: 'lohajang', name: 'লৌহজং' },
      { id: 'sirajdikhan', name: 'সিরাজদিখান' },
      { id: 'sreenagar', name: 'শ্রীনগর' },
      { id: 'tongibari', name: 'টংগীবাড়ী' },
    ],
  },
  {
    id: 'narsingdi',
    name: 'নরসিংদী',
    division: 'ঢাকা',
    upazilas: [
      { id: 'narsingdi-sadar', name: 'নরসিংদী সদর' },
      { id: 'belabo', name: 'বেলাব' },
      { id: 'monohardi', name: 'মনোহরদী' },
      { id: 'palash', name: 'পলাশ' },
      { id: 'raipura', name: 'রায়পুরা' },
      { id: 'shibpur', name: 'শিবপুর' },
    ],
  },
  {
    id: 'rajbari',
    name: 'রাজবাড়ী',
    division: 'ঢাকা',
    upazilas: [
      { id: 'rajbari-sadar', name: 'রাজবাড়ী সদর' },
      { id: 'baliakandi', name: 'বালিয়াকান্দি' },
      { id: 'goalandaghat', name: 'গোয়ালন্দ' },
      { id: 'kalukhali', name: 'কালুখালী' },
      { id: 'pangsha', name: 'পাংশা' },
    ],
  },
  {
    id: 'madaripur',
    name: 'মাদারীপুর',
    division: 'ঢাকা',
    upazilas: [
      { id: 'madaripur-sadar', name: 'মাদারীপুর সদর' },
      { id: 'kalkini', name: 'কালকিনি' },
      { id: 'rajoir', name: 'রাজৈর' },
      { id: 'shibchar', name: 'শিবচর' },
    ],
  },
  {
    id: 'gopalganj',
    name: 'গোপালগঞ্জ',
    division: 'ঢাকা',
    upazilas: [
      { id: 'gopalganj-sadar', name: 'গোপালগঞ্জ সদর' },
      { id: 'kashiani', name: 'কাশিয়ানী' },
      { id: 'kotalipara', name: 'কোটালীপাড়া' },
      { id: 'muksudpur', name: 'মুকসুদপুর' },
      { id: 'tungipara', name: 'টুঙ্গিপাড়া' },
    ],
  },
  {
    id: 'faridpur',
    name: 'ফরিদপুর',
    division: 'ঢাকা',
    upazilas: [
      { id: 'faridpur-sadar', name: 'ফরিদপুর সদর' },
      { id: 'alfadanga', name: 'আলফাডাঙ্গা' },
      { id: 'bhanga', name: 'ভাঙ্গা' },
      { id: 'boalmari', name: 'বোয়ালমারী' },
      { id: 'charbhadrasan', name: 'চরভদ্রাসন' },
      { id: 'madhukhali', name: 'মধুখালী' },
      { id: 'nagarkanda', name: 'নগরকান্দা' },
      { id: 'sadarpur', name: 'সদরপুর' },
      { id: 'saltha', name: 'সালথা' },
    ],
  },
  {
    id: 'shariatpur',
    name: 'শরীয়তপুর',
    division: 'ঢাকা',
    upazilas: [
      { id: 'shariatpur-sadar', name: 'শরীয়তপুর সদর' },
      { id: 'damudya', name: 'ডামুড্যা' },
      { id: 'gosairhat', name: 'গোসাইরহাট' },
      { id: 'naria', name: 'নড়িয়া' },
      { id: 'vejerganj', name: 'ভেদরগঞ্জ' },
      { id: 'zanjira', name: 'জাজিরা' },
    ],
  },
  // চট্টগ্রাম বিভাগ
  {
    id: 'chattogram',
    name: 'চট্টগ্রাম',
    division: 'চট্টগ্রাম',
    upazilas: [
      { id: 'chattogram-sadar', name: 'চট্টগ্রাম সদর' },
      { id: 'anwara', name: 'আনোয়ারা' },
      { id: 'boalkhali', name: 'বোয়ালখালী' },
      { id: 'chandanaish', name: 'চন্দনাইশ' },
      { id: 'fatikchhari', name: 'ফটিকছড়ি' },
      { id: 'hathazari', name: 'হাটহাজারী' },
      { id: 'karnaphuli', name: 'কর্ণফুলী' },
      { id: 'lohagara', name: 'লোহাগাড়া' },
      { id: 'mirsharai', name: 'মীরসরাই' },
      { id: 'patiya', name: 'পটিয়া' },
      { id: 'rangunia', name: 'রাঙ্গুনিয়া' },
      { id: 'raozan', name: 'রাউজান' },
      { id: 'sandwip', name: 'সন্দ্বীপ' },
      { id: 'satkania', name: 'সাতকানিয়া' },
      { id: 'sitakunda', name: 'সীতাকুণ্ড' },
    ],
  },
  {
    id: 'coxsbazar',
    name: "কক্সবাজার",
    division: 'চট্টগ্রাম',
    upazilas: [
      { id: 'coxsbazar-sadar', name: "কক্সবাজার সদর" },
      { id: 'chakaria', name: 'চকরিয়া' },
      { id: 'kutubdia', name: 'কুতুবদিয়া' },
      { id: 'maheshkhali', name: 'মহেশখালী' },
      { id: 'pekua', name: 'পেকুয়া' },
      { id: 'ramu', name: 'রামু' },
      { id: 'teknaf', name: 'টেকনাফ' },
      { id: 'ukhia', name: 'উখিয়া' },
    ],
  },
  {
    id: 'rangamati',
    name: 'রাঙ্গামাটি',
    division: 'চট্টগ্রাম',
    upazilas: [
      { id: 'rangamati-sadar', name: 'রাঙ্গামাটি সদর' },
      { id: 'bagaichhari', name: 'বাঘাইছড়ি' },
      { id: 'barkal', name: 'বরকল' },
      { id: 'belaichhari', name: 'বিলাইছড়ি' },
      { id: 'juraichhari', name: 'জুরাইছড়ি' },
      { id: 'kaptai', name: 'কাপ্তাই' },
      { id: 'kawkhali', name: 'কাউখালী' },
      { id: 'langadu', name: 'লংগদু' },
      { id: 'naniarchar', name: 'নানিয়ারচর' },
      { id: 'rajasthali', name: 'রাজস্থলী' },
    ],
  },
  {
    id: 'khagrachhari',
    name: 'খাগড়াছড়ি',
    division: 'চট্টগ্রাম',
    upazilas: [
      { id: 'khagrachhari-sadar', name: 'খাগড়াছড়ি সদর' },
      { id: 'dighinala', name: 'দিঘীনালা' },
      { id: 'guimara', name: 'গুইমারা' },
      { id: 'lakshmichhari', name: 'লক্ষ্মীছড়ি' },
      { id: 'mahalchhari', name: 'মহালছড়ি' },
      { id: 'manikchhari', name: 'মানিকছড়ি' },
      { id: 'matiranga', name: 'মাটিরাঙ্গা' },
      { id: 'panchhari', name: 'পানছড়ি' },
      { id: 'ramgarh', name: 'রামগড়' },
    ],
  },
  {
    id: 'bandarban',
    name: 'বান্দরবান',
    division: 'চট্টগ্রাম',
    upazilas: [
      { id: 'bandarban-sadar', name: 'বান্দরবান সদর' },
      { id: 'alikadam', name: 'আলীকদম' },
      { id: 'lama', name: 'লামা' },
      { id: 'naikhongchhari', name: 'নাইক্ষ্যংছড়ি' },
      { id: 'rowangchhari', name: 'রোয়াংছড়ি' },
      { id: 'ruma', name: 'রুমা' },
      { id: 'thanchi', name: 'থানচি' },
    ],
  },
  {
    id: 'cumilla',
    name: 'কুমিল্লা',
    division: 'চট্টগ্রাম',
    upazilas: [
      { id: 'cumilla-sadar', name: 'কুমিল্লা সদর' },
      { id: 'barura', name: 'বরুড়া' },
      { id: 'brahmanpara', name: 'ব্রাহ্মণপাড়া' },
      { id: 'burichang', name: 'বুড়িচং' },
      { id: 'chandina', name: 'চান্দিনা' },
      { id: 'chauddagram', name: 'চৌদ্দগ্রাম' },
      { id: 'daudkandi', name: 'দাউদকান্দি' },
      { id: 'debidwar', name: 'দেবীদ্বার' },
      { id: 'homna', name: 'হোমনা' },
      { id: 'laksam', name: 'লাকসাম' },
      { id: 'lalmai', name: 'লালমাই' },
      { id: 'meghna', name: 'মেঘনা' },
      { id: 'monoharganj', name: 'মনোহরগঞ্জ' },
      { id: 'muradnagar', name: 'মুরাদনগর' },
      { id: 'nangalkot', name: 'নাঙ্গলকোট' },
      { id: 'titas', name: 'তিতাস' },
    ],
  },
  {
    id: 'feni',
    name: 'ফেনী',
    division: 'চট্টগ্রাম',
    upazilas: [
      { id: 'feni-sadar', name: 'ফেনী সদর' },
      { id: 'chhagalnaiya', name: 'ছাগলনাইয়া' },
      { id: 'daganbhuiyan', name: 'দাগনভূঞা' },
      { id: 'parshuram', name: 'পরশুরাম' },
      { id: 'sonagazi', name: 'সোনাগাজী' },
      { id: 'fulgazi', name: 'ফুলগাজী' },
    ],
  },
  {
    id: 'noakhali',
    name: 'নোয়াখালী',
    division: 'চট্টগ্রাম',
    upazilas: [
      { id: 'noakhali-sadar', name: 'নোয়াখালী সদর' },
      { id: 'begumganj', name: 'বেগমগঞ্জ' },
      { id: 'chatkhil', name: 'চাটখিল' },
      { id: 'companiganj', name: 'কোম্পানীগঞ্জ' },
      { id: 'hatiya', name: 'হাতিয়া' },
      { id: 'kabirhat', name: 'কবিরহাট' },
      { id: 'senbag', name: 'সেনবাগ' },
      { id: 'sonaimuri', name: 'সোনাইমুড়ী' },
      { id: 'subarnachar', name: 'সুবর্ণচর' },
    ],
  },
  {
    id: 'lakshmipur',
    name: 'লক্ষ্মীপুর',
    division: 'চট্টগ্রাম',
    upazilas: [
      { id: 'lakshmipur-sadar', name: 'লক্ষ্মীপুর সদর' },
      { id: 'kamalnagar', name: 'কমলনগর' },
      { id: 'raipur', name: 'রায়পুর' },
      { id: 'ramganj', name: 'রামগঞ্জ' },
      { id: 'ramgati', name: 'রামগতি' },
    ],
  },
  {
    id: 'brahmanbaria',
    name: 'ব্রাহ্মণবাড়িয়া',
    division: 'চট্টগ্রাম',
    upazilas: [
      { id: 'brahmanbaria-sadar', name: 'ব্রাহ্মণবাড়িয়া সদর' },
      { id: 'akhaura', name: 'আখাউড়া' },
      { id: 'ashuganj', name: 'আশুগঞ্জ' },
      { id: 'bancharampur', name: 'বাঞ্ছারামপুর' },
      { id: 'bijoynagar', name: 'বিজয়নগর' },
      { id: 'kasba', name: 'কসবা' },
      { id: 'nabinagar', name: 'নবীনগর' },
      { id: 'nasirnagar', name: 'নাসিরনগর' },
      { id: 'sarail', name: 'সরাইল' },
    ],
  },
  {
    id: 'chandpur',
    name: 'চাঁদপুর',
    division: 'চট্টগ্রাম',
    upazilas: [
      { id: 'chandpur-sadar', name: 'চাঁদপুর সদর' },
      { id: 'faridganj', name: 'ফরিদগঞ্জ' },
      { id: 'haimchar', name: 'হাইমচর' },
      { id: 'haziganj', name: 'হাজীগঞ্জ' },
      { id: 'kachua', name: 'কচুয়া' },
      { id: 'matlab-north', name: 'মতলব উত্তর' },
      { id: 'matlab-south', name: 'মতলব দক্ষিণ' },
      { id: 'shahrasti', name: 'শাহরাস্তি' },
    ],
  },
  // রাজশাহী বিভাগ
  {
    id: 'rajshahi',
    name: 'রাজশাহী',
    division: 'রাজশাহী',
    upazilas: [
      { id: 'rajshahi-sadar', name: 'রাজশাহী সদর' },
      { id: 'bagha', name: 'বাঘা' },
      { id: 'bagmara', name: 'বাগমারা' },
      { id: 'charghat', name: 'চারঘাট' },
      { id: 'durgapur', name: 'দুর্গাপুর' },
      { id: 'godagari', name: 'গোদাগাড়ী' },
      { id: 'mohanpur', name: 'মোহনপুর' },
      { id: 'paba', name: 'পবা' },
      { id: 'puthia', name: 'পুঠিয়া' },
      { id: 'tanore', name: 'তানোর' },
    ],
  },
  {
    id: 'chapainawabganj',
    name: 'চাঁপাইনবাবগঞ্জ',
    division: 'রাজশাহী',
    upazilas: [
      { id: 'chapainawabganj-sadar', name: 'চাঁপাইনবাবগঞ্জ সদর' },
      { id: 'bholahat', name: 'ভোলাহাট' },
      { id: 'gomastapur', name: 'গোমস্তাপুর' },
      { id: 'nachole', name: 'নাচোল' },
      { id: 'shibganj', name: 'শিবগঞ্জ' },
    ],
  },
  {
    id: 'naogaon',
    name: 'নওগাঁ',
    division: 'রাজশাহী',
    upazilas: [
      { id: 'naogaon-sadar', name: 'নওগাঁ সদর' },
      { id: 'atrai', name: 'আত্রাই' },
      { id: 'badalgachhi', name: 'বদলগাছী' },
      { id: 'dhamoirhat', name: 'ধামইরহাট' },
      { id: 'manda', name: 'মান্দা' },
      { id: 'mahadebpur', name: 'মহাদেবপুর' },
      { id: 'niamatpur', name: 'নিয়ামতপুর' },
      { id: 'patnitala', name: 'পত্নীতলা' },
      { id: 'porsha', name: 'পোরশা' },
      { id: 'raninagar', name: 'রাণীনগর' },
      { id: 'sapahar', name: 'সাপাহার' },
    ],
  },
  {
    id: 'natore',
    name: 'নাটোর',
    division: 'রাজশাহী',
    upazilas: [
      { id: 'natore-sadar', name: 'নাটোর সদর' },
      { id: 'baraigram', name: 'বড়াইগ্রাম' },
      { id: 'bagatipara', name: 'বাগাতিপাড়া' },
      { id: 'gurudaspur', name: 'গুরুদাসপুর' },
      { id: 'lalpur', name: 'লালপুর' },
      { id: 'singra', name: 'সিংড়া' },
    ],
  },
  {
    id: 'pabna',
    name: 'পাবনা',
    division: 'রাজশাহী',
    upazilas: [
      { id: 'pabna-sadar', name: 'পাবনা সদর' },
      { id: 'atgharia', name: 'আটঘরিয়া' },
      { id: 'bera', name: 'বেড়া' },
      { id: 'bhangura', name: 'ভাঙ্গুড়া' },
      { id: 'chatmohar', name: 'চাটমোহর' },
      { id: 'faridpur-pabna', name: 'ফরিদপুর' },
      { id: 'ishwardi', name: 'ঈশ্বরদী' },
      { id: 'santhia', name: 'সাঁথিয়া' },
      { id: 'sujanagar', name: 'সুজানগর' },
    ],
  },
  {
    id: 'sirajganj',
    name: 'সিরাজগঞ্জ',
    division: 'রাজশাহী',
    upazilas: [
      { id: 'sirajganj-sadar', name: 'সিরাজগঞ্জ সদর' },
      { id: 'belkuchi', name: 'বেলকুচি' },
      { id: 'chauhali', name: 'চৌহালী' },
      { id: 'kamarkhanda', name: 'কামারখন্দ' },
      { id: 'kazipur', name: 'কাজীপুর' },
      { id: 'raiganj', name: 'রায়গঞ্জ' },
      { id: 'shahjadpur', name: 'শাহজাদপুর' },
      { id: 'tarash', name: 'তাড়াশ' },
      { id: 'ullapara', name: 'উল্লাপাড়া' },
    ],
  },
  {
    id: 'bogura',
    name: 'বগুড়া',
    division: 'রাজশাহী',
    upazilas: [
      { id: 'bogura-sadar', name: 'বগুড়া সদর' },
      { id: 'adamdighi', name: 'আদমদিঘী' },
      { id: 'dhunat', name: 'ধুনট' },
      { id: 'dupchanchia', name: 'দুপচাঁচিয়া' },
      { id: 'gabtali', name: 'গাবতলী' },
      { id: 'kahaloo', name: 'কাহালু' },
      { id: 'nandigram', name: 'নন্দীগ্রাম' },
      { id: 'sariatpur', name: 'শাজাহানপুর' },
      { id: 'sherpur-bogura', name: 'শেরপুর' },
      { id: 'shibganj-bogura', name: 'শিবগঞ্জ' },
      { id: 'sonatala', name: 'সোনাতলা' },
    ],
  },
  {
    id: 'joypurhat',
    name: 'জয়পুরহাট',
    division: 'রাজশাহী',
    upazilas: [
      { id: 'joypurhat-sadar', name: 'জয়পুরহাট সদর' },
      { id: 'akkelpur', name: 'আক্কেলপুর' },
      { id: 'kalai', name: 'কালাই' },
      { id: 'khetlal', name: 'ক্ষেতলাল' },
      { id: 'panchbibi', name: 'পাঁচবিবি' },
    ],
  },
  // সিলেট বিভাগ
  {
    id: 'sylhet',
    name: 'সিলেট',
    division: 'সিলেট',
    upazilas: [
      { id: 'sylhet-sadar', name: 'সিলেট সদর' },
      { id: 'balaganj', name: 'বালাগঞ্জ' },
      { id: 'beanibazar', name: 'বিয়ানীবাজার' },
      { id: 'bishwanath', name: 'বিশ্বনাথ' },
      { id: 'companiganj-sylhet', name: 'কোম্পানীগঞ্জ' },
      { id: 'fenchuganj', name: 'ফেঞ্চুগঞ্জ' },
      { id: 'golapganj', name: 'গোলাপগঞ্জ' },
      { id: 'gowainghat', name: 'গোয়াইনঘাট' },
      { id: 'jaintiapur', name: 'জৈন্তাপুর' },
      { id: 'kanaighat', name: 'কানাইঘাট' },
      { id: 'osmani-nagar', name: 'ওসমানী নগর' },
      { id: 'south-surma', name: 'দক্ষিণ সুরমা' },
      { id: 'zakiganj', name: 'জকিগঞ্জ' },
    ],
  },
  {
    id: 'moulvibazar',
    name: 'মৌলভীবাজার',
    division: 'সিলেট',
    upazilas: [
      { id: 'moulvibazar-sadar', name: 'মৌলভীবাজার সদর' },
      { id: 'barlekha', name: 'বড়লেখা' },
      { id: 'juri', name: 'জুড়ী' },
      { id: 'kamalganj', name: 'কমলগঞ্জ' },
      { id: 'kulaura', name: 'কুলাউড়া' },
      { id: 'rajnagar', name: 'রাজনগর' },
      { id: 'sreemangal', name: 'শ্রীমঙ্গল' },
    ],
  },
  {
    id: 'habiganj',
    name: 'হবিগঞ্জ',
    division: 'সিলেট',
    upazilas: [
      { id: 'habiganj-sadar', name: 'হবিগঞ্জ সদর' },
      { id: 'ajmiriganj', name: 'আজমিরীগঞ্জ' },
      { id: 'bahubal', name: 'বাহুবল' },
      { id: 'baniachong', name: 'বানিয়াচং' },
      { id: 'chunarughat', name: 'চুনারুঘাট' },
      { id: 'lakhai', name: 'লাখাই' },
      { id: 'madhabpur', name: 'মাধবপুর' },
      { id: 'nabiganj', name: 'নবীগঞ্জ' },
    ],
  },
  {
    id: 'sunamganj',
    name: 'সুনামগঞ্জ',
    division: 'সিলেট',
    upazilas: [
      { id: 'sunamganj-sadar', name: 'সুনামগঞ্জ সদর' },
      { id: 'bishwamvarpur', name: 'বিশ্বম্ভরপুর' },
      { id: 'chhatak', name: 'ছাতক' },
      { id: 'derai', name: 'দিরাই' },
      { id: 'dharampasha', name: 'ধর্মপাশা' },
      { id: 'dowarabazar', name: 'দোয়ারাবাজার' },
      { id: 'jamalganj', name: 'জামালগঞ্জ' },
      { id: 'shalla', name: 'শাল্লা' },
      { id: 'tahirpur', name: 'তাহিরপুর' },
    ],
  },
  // খুলনা বিভাগ
  {
    id: 'khulna',
    name: 'খুলনা',
    division: 'খুলনা',
    upazilas: [
      { id: 'khulna-sadar', name: 'খুলনা সদর' },
      { id: 'batiaghata', name: 'বটিয়াঘাটা' },
      { id: 'dacope', name: 'ডাকোপ' },
      { id: 'dumuria', name: 'ডুমুরিয়া' },
      { id: 'dighalia', name: 'দিঘলিয়া' },
      { id: 'koyra', name: 'কয়রা' },
      { id: 'paikgachha', name: 'পাইকগাছা' },
      { id: 'phultala', name: 'ফুলতলা' },
      { id: 'rupsha', name: 'রূপসা' },
      { id: 'terokhada', name: 'তেরখাদা' },
    ],
  },
  {
    id: 'bagerhat',
    name: 'বাগেরহাট',
    division: 'খুলনা',
    upazilas: [
      { id: 'bagerhat-sadar', name: 'বাগেরহাট সদর' },
      { id: 'chitalmari', name: 'চিতলমারী' },
      { id: 'fakirhat', name: 'ফকিরহাট' },
      { id: 'kachua-bagerhat', name: 'কচুয়া' },
      { id: 'mollahat', name: 'মোল্লাহাট' },
      { id: 'mongla', name: 'মোংলা' },
      { id: 'morrelganj', name: 'মোড়েলগঞ্জ' },
      { id: 'rampal', name: 'রামপাল' },
      { id: 'sarankhola', name: 'শরণখোলা' },
    ],
  },
  {
    id: 'satkhira',
    name: 'সাতক্ষীরা',
    division: 'খুলনা',
    upazilas: [
      { id: 'satkhira-sadar', name: 'সাতক্ষীরা সদর' },
      { id: 'assasuni', name: 'আশাশুনি' },
      { id: 'debhata', name: 'দেবহাটা' },
      { id: 'kalaroa', name: 'কলারোয়া' },
      { id: 'kaliganj-satkhira', name: 'কালিগঞ্জ' },
      { id: 'shyamnagar', name: 'শ্যামনগর' },
      { id: 'tala', name: 'তালা' },
    ],
  },
  {
    id: 'jessore',
    name: 'যশোর',
    division: 'খুলনা',
    upazilas: [
      { id: 'jessore-sadar', name: 'যশোর সদর' },
      { id: 'abhaynagar', name: 'অভয়নগর' },
      { id: 'bagherpara', name: 'বাঘারপাড়া' },
      { id: 'chaugachha', name: 'চৌগাছা' },
      { id: 'jhikargachha', name: 'ঝিকরগাছা' },
      { id: 'keshabpur', name: 'কেশবপুর' },
      { id: 'manirampur', name: 'মণিরামপুর' },
      { id: 'sharsha', name: 'শার্শা' },
    ],
  },
  {
    id: 'magura',
    name: 'মাগুরা',
    division: 'খুলনা',
    upazilas: [
      { id: 'magura-sadar', name: 'মাগুরা সদর' },
      { id: 'mohammadpur', name: 'মোহাম্মদপুর' },
      { id: 'shalikha', name: 'শালিখা' },
      { id: 'sreepur-magura', name: 'শ্রীপুর' },
    ],
  },
  {
    id: 'narail',
    name: 'নড়াইল',
    division: 'খুলনা',
    upazilas: [
      { id: 'narail-sadar', name: 'নড়াইল সদর' },
      { id: 'kalia', name: 'কালিয়া' },
      { id: 'lohagara-narail', name: 'লোহাগড়া' },
    ],
  },
  {
    id: 'jhenaidah',
    name: 'ঝিনাইদহ',
    division: 'খুলনা',
    upazilas: [
      { id: 'jhenaidah-sadar', name: 'ঝিনাইদহ সদর' },
      { id: 'harinakunda', name: 'হরিণাকুণ্ডু' },
      { id: 'kaliganj-jhenaidah', name: 'কালীগঞ্জ' },
      { id: 'kotchandpur', name: 'কোটচাঁদপুর' },
      { id: 'maheshpur', name: 'মহেশপুর' },
      { id: 'shailkupa', name: 'শৈলকুপা' },
    ],
  },
  {
    id: 'chuadanga',
    name: 'চুয়াডাঙ্গা',
    division: 'খুলনা',
    upazilas: [
      { id: 'chuadanga-sadar', name: 'চুয়াডাঙ্গা সদর' },
      { id: 'alamdanga', name: 'আলমডাঙ্গা' },
      { id: 'damurhuda', name: 'দামুড়হুদা' },
      { id: 'jibannagar', name: 'জীবননগর' },
    ],
  },
  {
    id: 'kushtia',
    name: 'কুষ্টিয়া',
    division: 'খুলনা',
    upazilas: [
      { id: 'kushtia-sadar', name: 'কুষ্টিয়া সদর' },
      { id: 'bheramara', name: 'ভেড়ামারা' },
      { id: 'daulatpur-kushtia', name: 'দৌলতপুর' },
      { id: 'khoksa', name: 'খোকসা' },
      { id: 'kumarkhali', name: 'কুমারখালী' },
      { id: 'mirpur-kushtia', name: 'মিরপুর' },
    ],
  },
  {
    id: 'meherpur',
    name: 'মেহেরপুর',
    division: 'খুলনা',
    upazilas: [
      { id: 'meherpur-sadar', name: 'মেহেরপুর সদর' },
      { id: 'gangni', name: 'গাংনী' },
      { id: 'mujibnagar', name: 'মুজিবনগর' },
    ],
  },
  // বরিশাল বিভাগ
  {
    id: 'barishal',
    name: 'বরিশাল',
    division: 'বরিশাল',
    upazilas: [
      { id: 'barishal-sadar', name: 'বরিশাল সদর' },
      { id: 'agailjhara', name: 'আগৈলঝাড়া' },
      { id: 'babuganj', name: 'বাবুগঞ্জ' },
      { id: 'bakerganj', name: 'বাকেরগঞ্জ' },
      { id: 'banaripara', name: 'বানারীপাড়া' },
      { id: 'gaurnadi', name: 'গৌরনদী' },
      { id: 'hizla', name: 'হিজলা' },
      { id: 'mehendiganj', name: 'মেহেন্দিগঞ্জ' },
      { id: 'muladi', name: 'মুলাদী' },
      { id: 'wazirpur', name: 'উজিরপুর' },
    ],
  },
  {
    id: 'bhola',
    name: 'ভোলা',
    division: 'বরিশাল',
    upazilas: [
      { id: 'bhola-sadar', name: 'ভোলা সদর' },
      { id: 'borhanuddin', name: 'বোরহানউদ্দিন' },
      { id: 'char-fasson', name: 'চরফ্যাশন' },
      { id: 'daulatkhan', name: 'দৌলতখান' },
      { id: 'lalmohan', name: 'লালমোহন' },
      { id: 'manpura', name: 'মনপুরা' },
      { id: 'tazumuddin', name: 'তজুমদ্দিন' },
    ],
  },
  {
    id: 'patuakhali',
    name: 'পটুয়াখালী',
    division: 'বরিশাল',
    upazilas: [
      { id: 'patuakhali-sadar', name: 'পটুয়াখালী সদর' },
      { id: 'bauphal', name: 'বাউফল' },
      { id: 'dashmina', name: 'দশমিনা' },
      { id: 'galachipa', name: 'গলাচিপা' },
      { id: 'kalapara', name: 'কলাপাড়া' },
      { id: 'mirzaganj', name: 'মির্জাগঞ্জ' },
      { id: 'rangabali', name: 'রাঙ্গাবালী' },
    ],
  },
  {
    id: 'barguna',
    name: 'বরগুনা',
    division: 'বরিশাল',
    upazilas: [
      { id: 'barguna-sadar', name: 'বরগুনা সদর' },
      { id: 'amtali', name: 'আমতলী' },
      { id: 'bamna', name: 'বামনা' },
      { id: 'betagi', name: 'বেতাগী' },
      { id: 'pathorghata', name: 'পাথরঘাটা' },
      { id: 'taltali', name: 'তালতলী' },
    ],
  },
  {
    id: 'pirojpur',
    name: 'পিরোজপুর',
    division: 'বরিশাল',
    upazilas: [
      { id: 'pirojpur-sadar', name: 'পিরোজপুর সদর' },
      { id: 'bhandaria', name: 'ভান্ডারিয়া' },
      { id: 'kawkhali-pirojpur', name: 'কাউখালী' },
      { id: 'mathbaria', name: 'মঠবাড়িয়া' },
      { id: 'nazirpur', name: 'নাজিরপুর' },
      { id: 'nesarabad', name: 'নেছারাবাদ' },
      { id: 'zianagar', name: 'জিয়ানগর' },
    ],
  },
  {
    id: 'jhalokati',
    name: 'ঝালকাঠি',
    division: 'বরিশাল',
    upazilas: [
      { id: 'jhalokati-sadar', name: 'ঝালকাঠি সদর' },
      { id: 'kathalia', name: 'কাঠালিয়া' },
      { id: 'nalchity', name: 'নলছিটি' },
      { id: 'rajapur', name: 'রাজাপুর' },
    ],
  },
  // ময়মনসিংহ বিভাগ
  {
    id: 'mymensingh',
    name: 'ময়মনসিংহ',
    division: 'ময়মনসিংহ',
    upazilas: [
      { id: 'mymensingh-sadar', name: 'ময়মনসিংহ সদর' },
      { id: 'bhaluka', name: 'ভালুকা' },
      { id: 'dhobaura', name: 'ধোবাউড়া' },
      { id: 'fulbaria', name: 'ফুলবাড়িয়া' },
      { id: 'gaffargaon', name: 'গফরগাঁও' },
      { id: 'gauripur', name: 'গৌরীপুর' },
      { id: 'haluaghat', name: 'হালুয়াঘাট' },
      { id: 'ishwarganj', name: 'ঈশ্বরগঞ্জ' },
      { id: 'muktagachha', name: 'মুক্তাগাছা' },
      { id: 'nandail', name: 'নান্দাইল' },
      { id: 'phulpur', name: 'ফুলপুর' },
      { id: 'tarakanda', name: 'তারাকান্দা' },
      { id: 'trishal', name: 'ত্রিশাল' },
    ],
  },
  {
    id: 'jamalpur',
    name: 'জামালপুর',
    division: 'ময়মনসিংহ',
    upazilas: [
      { id: 'jamalpur-sadar', name: 'জামালপুর সদর' },
      { id: 'bakshiganj', name: 'বকশীগঞ্জ' },
      { id: 'dewanganj', name: 'দেওয়ানগঞ্জ' },
      { id: 'islampur', name: 'ইসলামপুর' },
      { id: 'madarganj', name: 'মাদারগঞ্জ' },
      { id: 'melandaha', name: 'মেলান্দহ' },
      { id: 'sarishabari', name: 'সরিষাবাড়ী' },
    ],
  },
  {
    id: 'netrokona',
    name: 'নেত্রকোনা',
    division: 'ময়মনসিংহ',
    upazilas: [
      { id: 'netrokona-sadar', name: 'নেত্রকোনা সদর' },
      { id: 'atpara', name: 'আটপাড়া' },
      { id: 'barhatta', name: 'বারহাট্টা' },
      { id: 'durgapur-netrokona', name: 'দুর্গাপুর' },
      { id: 'kalmakanda', name: 'কলমাকান্দা' },
      { id: 'kendua', name: 'কেন্দুয়া' },
      { id: 'khaliajuri', name: 'খালিয়াজুরী' },
      { id: 'madan', name: 'মদন' },
      { id: 'mohanganj', name: 'মোহনগঞ্জ' },
      { id: 'purbadhala', name: 'পূর্বধলা' },
    ],
  },
  {
    id: 'kishoreganj',
    name: 'কিশোরগঞ্জ',
    division: 'ময়মনসিংহ',
    upazilas: [
      { id: 'kishoreganj-sadar', name: 'কিশোরগঞ্জ সদর' },
      { id: 'austagram', name: 'অষ্টগ্রাম' },
      { id: 'bajitpur', name: 'বাজিতপুর' },
      { id: 'bhairab', name: 'ভৈরব' },
      { id: 'hossainpur', name: 'হোসেনপুর' },
      { id: 'itna', name: 'ইটনা' },
      { id: 'karimganj', name: 'করিমগঞ্জ' },
      { id: 'katiadi', name: 'কটিয়াদী' },
      { id: 'kuliarchar', name: 'কুলিয়ারচর' },
      { id: 'mithamain', name: 'মিঠামইন' },
      { id: 'nikli', name: 'নিকলী' },
      { id: 'pakundia', name: 'পাকুন্দিয়া' },
      { id: 'tarail', name: 'তাড়াইল' },
    ],
  },
  {
    id: 'tangail',
    name: 'টাঙ্গাইল',
    division: 'ময়মনসিংহ',
    upazilas: [
      { id: 'tangail-sadar', name: 'টাঙ্গাইল সদর' },
      { id: 'basail', name: 'বাসাইল' },
      { id: 'bhuapur', name: 'ভূঞাপুর' },
      { id: 'delduar', name: 'দেলদুয়ার' },
      { id: 'dhanbari', name: 'ধনবাড়ী' },
      { id: 'ghatail', name: 'ঘাটাইল' },
      { id: 'gopalpur', name: 'গোপালপুর' },
      { id: 'kalihati', name: 'কালিহাতী' },
      { id: 'madhupur', name: 'মধুপুর' },
      { id: 'mirzapur', name: 'মির্জাপুর' },
      { id: 'nagarpur', name: 'নাগরপুর' },
      { id: 'sakhipur', name: 'সখিপুর' },
    ],
  },
  // রংপুর বিভাগ
  {
    id: 'rangpur',
    name: 'রংপুর',
    division: 'রংপুর',
    upazilas: [
      { id: 'rangpur-sadar', name: 'রংপুর সদর' },
      { id: 'badarganj', name: 'বদরগঞ্জ' },
      { id: 'gangachara', name: 'গঙ্গাচড়া' },
      { id: 'kaunia', name: 'কাউনিয়া' },
      { id: 'mithapukur', name: 'মিঠাপুকুর' },
      { id: 'pirgachha', name: 'পীরগাছা' },
      { id: 'pirganj-rangpur', name: 'পীরগঞ্জ' },
      { id: 'taraganj', name: 'তারাগঞ্জ' },
    ],
  },
  {
    id: 'dinajpur',
    name: 'দিনাজপুর',
    division: 'রংপুর',
    upazilas: [
      { id: 'dinajpur-sadar', name: 'দিনাজপুর সদর' },
      { id: 'birampur', name: 'বিরামপুর' },
      { id: 'birganj', name: 'বীরগঞ্জ' },
      { id: 'biral', name: 'বিরল' },
      { id: 'bochaganj', name: 'বোচাগঞ্জ' },
      { id: 'chirirbandar', name: 'চিরিরবন্দর' },
      { id: 'fulbari-dinajpur', name: 'ফুলবাড়ী' },
      { id: 'ghoraghat', name: 'ঘোড়াঘাট' },
      { id: 'hakimpur', name: 'হাকিমপুর' },
      { id: 'kaharole', name: 'কাহারোল' },
      { id: 'khansama', name: 'খানসামা' },
      { id: 'nawabganj-dinajpur', name: 'নবাবগঞ্জ' },
      { id: 'parbatipur', name: 'পার্বতীপুর' },
    ],
  },
  {
    id: 'gaibandha',
    name: 'গাইবান্ধা',
    division: 'রংপুর',
    upazilas: [
      { id: 'gaibandha-sadar', name: 'গাইবান্ধা সদর' },
      { id: 'fulchhari', name: 'ফুলছড়ি' },
      { id: 'gobindaganj', name: 'গোবিন্দগঞ্জ' },
      { id: 'palashbari', name: 'পলাশবাড়ী' },
      { id: 'sadullapur', name: 'সাদুল্লাপুর' },
      { id: 'sagata', name: 'সাঘাটা' },
      { id: 'sundarganj', name: 'সুন্দরগঞ্জ' },
    ],
  },
  {
    id: 'kurigram',
    name: 'কুড়িগ্রাম',
    division: 'রংপুর',
    upazilas: [
      { id: 'kurigram-sadar', name: 'কুড়িগ্রাম সদর' },
      { id: 'bhurungamari', name: 'ভুরুঙ্গামারী' },
      { id: 'char-rajibpur', name: 'চর রাজিবপুর' },
      { id: 'chilmari', name: 'চিলমারী' },
      { id: 'nageshwari', name: 'নাগেশ্বরী' },
      { id: 'phulbari-kurigram', name: 'ফুলবাড়ী' },
      { id: 'rajarhat', name: 'রাজারহাট' },
      { id: 'raumari', name: 'রৌমারী' },
      { id: 'ulipur', name: 'উলিপুর' },
    ],
  },
  {
    id: 'lalmonirhat',
    name: 'লালমনিরহাট',
    division: 'রংপুর',
    upazilas: [
      { id: 'lalmonirhat-sadar', name: 'লালমনিরহাট সদর' },
      { id: 'aditmari', name: 'আদিতমারী' },
      { id: 'hatibandha', name: 'হাতীবান্ধা' },
      { id: 'kaliganj-lalmonirhat', name: 'কালীগঞ্জ' },
      { id: 'patgram', name: 'পাটগ্রাম' },
    ],
  },
  {
    id: 'nilphamari',
    name: 'নীলফামারী',
    division: 'রংপুর',
    upazilas: [
      { id: 'nilphamari-sadar', name: 'নীলফামারী সদর' },
      { id: 'dimla', name: 'ডিমলা' },
      { id: 'domar', name: 'ডোমার' },
      { id: 'jaldhaka', name: 'জলঢাকা' },
      { id: 'kishoreganj-nilphamari', name: 'কিশোরগঞ্জ' },
      { id: 'saidpur', name: 'সৈয়দপুর' },
    ],
  },
  {
    id: 'panchagarh',
    name: 'পঞ্চগড়',
    division: 'রংপুর',
    upazilas: [
      { id: 'panchagarh-sadar', name: 'পঞ্চগড় সদর' },
      { id: 'atwari', name: 'আটোয়ারী' },
      { id: 'boda', name: 'বোদা' },
      { id: 'debiganj', name: 'দেবীগঞ্জ' },
      { id: 'tetulia', name: 'তেঁতুলিয়া' },
    ],
  },
  {
    id: 'thakurgaon',
    name: 'ঠাকুরগাঁও',
    division: 'রংপুর',
    upazilas: [
      { id: 'thakurgaon-sadar', name: 'ঠাকুরগাঁও সদর' },
      { id: 'baliadangi', name: 'বালিয়াডাঙ্গী' },
      { id: 'haripur', name: 'হরিপুর' },
      { id: 'pirganj-thakurgaon', name: 'পীরগঞ্জ' },
      { id: 'ranisankail', name: 'রাণীশংকৈল' },
    ],
  },
  // ঢাকা বিভাগ - অতিরিক্ত
  {
    id: 'netrokona-extra',
    name: 'শেরপুর',
    division: 'ময়মনসিংহ',
    upazilas: [
      { id: 'sherpur-sadar', name: 'শেরপুর সদর' },
      { id: 'jhenaigati', name: 'ঝিনাইগাতী' },
      { id: 'nakla', name: 'নকলা' },
      { id: 'nalitabari', name: 'নালিতাবাড়ী' },
      { id: 'sreebardi', name: 'শ্রীবরদী' },
    ],
  },
]

export const DIVISIONS = [
  'ঢাকা',
  'চট্টগ্রাম',
  'রাজশাহী',
  'সিলেট',
  'খুলনা',
  'বরিশাল',
  'ময়মনসিংহ',
  'রংপুর',
]

export function getDistrictsByDivision(division: string): District[] {
  return BD_DISTRICTS.filter((d) => d.division === division)
}

export function getUpazilasByDistrict(districtId: string): Upazila[] {
  const district = BD_DISTRICTS.find((d) => d.id === districtId)
  return district?.upazilas || []
}
